version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./my-api:/var/www/html/my-api
      - ./pawpaw-fe-main:/var/www/html/pawpaw-fe-main
    restart: unless-stopped
    container_name: onix-website

  # Optional: Add database if needed
  # mysql:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: onix_db
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   restart: unless-stopped

# volumes:
#   mysql_data:
