# # k8s/backend/deployment.yaml
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend-deployment
#   labels:
#     app: backend
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#       - name: backend
#         image: your-dockerhub-username/pawpaw-backend:latest
#         ports:
#         - containerPort: 3001
#         env:
#         - name: DB_HOST
#           valueFrom:
#             configMapKeyRef:
#               name: app-config
#               key: db-host
#         - name: DB_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: app-secret
#               key: db-password
#         - name: DB_NAME
#           valueFrom:
#             configMapKeyRef:
#               name: app-config
#               key: db-name
#         resources:
#           limits:
#             memory: "512Mi"
#             cpu: "300m"
#           requests:
#             memory: "256Mi"
#             cpu: "150m"
