# # k8s/backend/service.yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-service
#   labels:
#     app: backend
# spec:
#   type: ClusterIP
#   ports:
#   - port: 3001
#     targetPort: 3001
#     protocol: TCP
#   selector:
#     app: backend
